"""First-run setup wizard with a simple GUI.

When no configured paper account exists, this wizard collects starting capital
and creates a paused OKX paper configuration. No exchange keys are required.

Falls back to terminal prompts if no display is available (headless server).
"""

import os
import sys
import math
from pathlib import Path

from dotenv import dotenv_values


def _get_env_path() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent / ".env"
    from bot import config
    return config.PROJECT_ROOT / ".env"


def _needs_setup() -> bool:
    env_path = _get_env_path()
    if not env_path.exists():
        return True
    values = dotenv_values(env_path)
    return not values.get("CAPITAL_USD")


def _write_env(data: dict):
    capital = float(data["capital"])
    if not math.isfinite(capital) or capital <= 0:
        raise ValueError("Paper capital must be a positive finite amount.")
    env_path = _get_env_path()
    content = f"""# TradingBot23 - auto-generated by setup wizard
BINANCE_API_KEY={data.get('binance_key', '')}
BINANCE_API_SECRET={data.get('binance_secret', '')}

TRADING_MODE=paper
ENGINE=futures
CAPITAL_USD={capital}
BOT_PROFILE=default

MAX_HOLD_DAYS=3
DIP_THRESHOLD_PCT=0.02
PER_TRADE_PCT=0.20
MAX_OPEN_TRADES=5
CHECK_INTERVAL_HOURS=1
AUTO_START_FUTURES=false
SETTINGS_CONFIRMED=false
TELEGRAM_ALLOW_CONTROL=false
PRE_TRADE_ANALYSIS_ENABLED=true
PRE_TRADE_MIN_SCORE=60
PRE_TRADE_BREAKDOWN_GUARD_ENABLED=true
PRE_TRADE_MAX_24H_DROP_PCT=8.0
PRE_TRADE_MAX_LOWER_CLOSE_STREAK=5
PRE_TRADE_MAX_BELOW_SMA20_PCT=1.5
PRE_TRADE_MIN_BREAKDOWN_REBOUND_PCT=1.0
BTC_REGIME_FILTER_PCT=-0.015
PAPER_SYMBOL_GUARD_ENABLED=true
PAPER_SYMBOL_GUARD_LOOKBACK_DAYS=30
PAPER_SYMBOL_GUARD_MAX_REALIZED_LOSS_USD=50
PAPER_SYMBOL_GUARD_EXPIRED_LOSS_USD=25
PAPER_SYMBOL_GUARD_BLOCK_LIQUIDATED=true
CRASH_ENTRY_GUARD_ENABLED=true
CRASH_EMERGENCY_SL_ENABLED=false
CRASH_BTC_TRIGGER_PCT=-0.04
CRASH_BTC_RECOVERY_PCT=-0.02
CRASH_SL_PCT=0.015

LEVERAGE=1
FUTURES_NET_TP_PCT=0.01
FUTURES_NET_SL_PCT=0.015
FUTURES_DIP_THRESHOLD_PCT=0.005
FUTURES_USE_SL=false
FUTURES_EXCHANGE=okx
FUTURES_MAX_ACCOUNT_LEVERAGE=3
FUTURES_CASH_RESERVE_PCT=0.20
LOCAL_BRIDGE_ENABLED=true
LOCAL_BRIDGE_PORT=7233
RISK_MAX_DAILY_LOSS_USD=0
RISK_MAX_OPEN_EXPOSURE_USD=0
RISK_MAX_LOSS_STREAK=0
OHVERLAY_ENABLED=false
OHVERLAY_WEBHOOK_URL=http://127.0.0.1:7277/message
OHVERLAY_SENDER=TradingBot23
OHVERLAY_TIMEOUT_SECS=2.0
OHVERLAY_MAX_CHARS=420

LOG_LEVEL=INFO
"""
    env_path.write_text(content, encoding="utf-8")


def run_gui_wizard() -> bool | None:
    """Create a paused paper account without requiring exchange credentials."""
    try:
        import tkinter as tk
        from tkinter import ttk, messagebox
    except ImportError:
        return None
    from bot.ui_theme import configure_styles, apply_window_brand, asset_path, FONT, MUTED

    completed = [False]
    try:
        root = tk.Tk()
    except tk.TclError:
        return None
    root.title("Trade23 Setup")
    root.geometry("480x390")
    root.resizable(False, False)
    configure_styles(root)
    apply_window_brand(root)
    frame = ttk.Frame(root, padding=28)
    frame.pack(fill="both", expand=True)
    mark = tk.PhotoImage(master=root, file=str(asset_path("ui/mark-40.png")))
    ttk.Label(frame, image=mark).pack(anchor="w", pady=(0, 12))
    ttk.Label(frame, text="Trade23", font=(FONT, 22, "bold")).pack(anchor="w")
    ttk.Label(frame, text="New paper account", foreground=MUTED).pack(anchor="w", pady=(0, 28))
    ttk.Label(frame, text="Capital (USD)", foreground=MUTED).pack(anchor="w", pady=(0, 6))
    capital_var = tk.StringVar(value="1000")
    cap_entry = ttk.Entry(frame, textvariable=capital_var, width=28, style="Settings.TEntry")
    cap_entry.pack(fill="x")
    cap_entry.focus_set()
    ttk.Label(frame, text="OKX  /  Futures paper", foreground=MUTED).pack(anchor="w", pady=14)

    def on_save():
        try:
            _write_env({"capital": capital_var.get().strip()})
        except (ValueError, OSError) as exc:
            messagebox.showerror("Account not created", str(exc), parent=root)
            return
        completed[0] = True
        root.destroy()

    buttons = ttk.Frame(frame)
    buttons.pack(fill="x", pady=(12, 0))
    ttk.Button(buttons, text="Create paper account", style="Primary.TButton", command=on_save).pack(side="left")
    ttk.Button(buttons, text="Cancel", style="Btn.TButton", command=root.destroy).pack(side="right")
    ttk.Label(frame, text="FutolTech", foreground=MUTED, font=(FONT, 8)).pack(side="bottom", anchor="w")
    root.mainloop()
    return completed[0]


def run_terminal_wizard() -> bool:
    """Fallback for headless paper installs."""
    print("\\n===== Trade23 Paper Setup =====\\n")
    capital = input("Paper capital USD [1000]: ").strip() or "1000"
    try:
        _write_env({"capital": capital})
    except (ValueError, OSError) as exc:
        print(f"Account not created: {exc}")
        return False
    print("Config saved. Review Settings before enabling scans.")
    return True


def ensure_setup() -> bool:
    """Run the setup wizard if needed. Returns True if bot can proceed."""
    if not _needs_setup():
        return True

    result = run_gui_wizard()
    return run_terminal_wizard() if result is None else result
